### ISSUE TITLE
Galvanizer Demo

### ISSUE THREAD

**Issue by diegomichel** [novotorium/galvanizer#20]
Demo how to edit pages to Kayla and Nathan.
- [x] [Fork](https://help.github.com/articles/fork-a-repo/) project
- [x] Development environment https://c9.io setup
- [x] [Make branch](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)
- [x] Make changes
- [x] [Make pull request](https://help.github.com/articles/creating-a-pull-request/#changing-the-branch-range-and-destination-repository)
- [x] [Review and accept changes](https://help.github.com/articles/about-pull-request-reviews/)
- [x] Create https://www.heroku.com/ Account
- [x] Generate GLASSFROG API KEY
- [x] Set Glassfrog API Key on c9.io
- [x] [Deploying changes to Heroku](https://devcenter.heroku.com/articles/git)
- [x] Upgrade heroku account - request domain change to Eduardo
- [x] How to set glassfrog api key([Config Vars](https://devcenter.heroku.com/articles/config-vars))

Stakeholders: @kaylasheely @NathanSnyder

**Comment by diegomichel** [comment]
Closing this @kaylasheely,

Here you can read more about the domain setup: https://devcenter.heroku.com/articles/custom-domains

Best Regards,
Diego Michel.

**Comment by kaylasheely** [comment]
Great, thank you!

Kayla Sheely
